from gluon.contrib.populate import populate
if db(db.auth_user).isempty():
     populate(db.auth_user,10)
     populate(db.t_t_semester,10)
     populate(db.t_t_request_comments,10)
     populate(db.t_t_contract,10)
     populate(db.t_t_parking,10)
     populate(db.t_t_room_type,10)
     populate(db.t_t_request_type,10)
     populate(db.t_t_apartment,10)
     populate(db.t_t_building,10)
     populate(db.t_t_request,10)
     populate(db.t_t_floor,10)
     populate(db.t_t_room,10)
     populate(db.t_t_apartment_type,10)
     populate(db.t_t_user_info,10)
